### ISSUE TITLE
swapping ftm to solidsex

### ISSUE THREAD

**Issue by baititing** [solidlyexchange/solidly#54]
hello,

i found a problem swapping from ftm to solidsex, it value is very small yet when converted back to solidsex to ftm, no value at all.

i just want to retrieve my ftm so i can stake to other farm.

https://ftmscan.com/tx/0xb4108132be81b4aec1f84e287cc2be9c6f8e0054f2668ac359157074bbc7c003?fbclid=IwAR3wRs5-PqyAnuUOA4lJf4qnejyhRIIS3E6w6WFe3e0RPkmdyPwGA9sFG5A

![image](https://user-images.githubusercontent.com/100401417/155662989-7f64f123-39e2-4e2a-be5d-66ecffdfe386.png)

thank you

**Comment by baititing** [comment]
![image](https://user-images.githubusercontent.com/100401417/155663436-72a5ddf1-e45d-40d8-96a7-d856fef2fe89.png)

**Comment by faead** [comment]
Your issue was likely due to very to very low liquidity in the pool. Unfortunately you wont be able to get your FTM back. The ratio of FTM to SOLIDsex would have been very high. Likely because people were trying to acquire SOLIDSex to farm it. 

In the future you should always check the quoted amount out and check the liquidity in the pool, especially for coins with alot of hype around them.
